routes:
    home: 'Default:home'
    concept: 'Default:concept'
    partners: 'Default:partners'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    registeraddress: 'Security:registeraddress'
    profile: 'Security:profile'
    PaypallPN: 'Security:PaypallPN'
    customize: 'Default:customize'

defaut_route: 'home'

db_config:
    name: 'SmartEat'
    host: '151.80.10.13:3306'
    user: 'smarteat'
    pass: 'I6e6yx9%'
