routes:
    home: 'Default:home'
    concept: 'Default:concept'
    partners: 'Default:partners'
    customize: 'Default:customize'
    profile: 'Security:profile'
    cart: 'Cart:viewcart'
    login: 'Security:login'
    logout: 'Security:logout'
    register: 'Security:register'
    registeraddress: 'Security:registeraddress'
    editcart: 'Cart:editcart'
    refreshcart: 'Cart:refreshcart'
    printaddress: 'Security:printaddress'
    PaypallPN: 'Security:PaypallPN'
    admin: 'Security:admin'

defaut_route: 'home'

db_config:
    name: 'SmartEat'
    host: '151.80.10.13:3306'
    user: 'smarteat'
    pass: 'I6e6yx9%'
